name: Update repos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_issue:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno run --unstable-temporal -A search.ts > file.md
          gh issue edit 4 -F file.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
