name: Update repos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  update_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
        deno run -A search.ts > file.md
        gh issue edit 4 -F file.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
